
package com.porto.portocom.portal.cliente.v1.wsdl.bcp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaDadosBCPWS", targetNamespace = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaDadosBCPWS {


    /**
     * 
     * @param codigoOrigemProposta
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param numeroContrato
     * @param suseps
     * @param nomePessoa
     * @param filtroContrato
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterContratoResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterContrato")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterContratoType")
    @ResponseWrapper(localName = "obterContratoResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterContratoResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoResponseType.Pessoa> obterContrato(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroContrato,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa,
        @WebParam(name = "codigoOrigemProposta", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String codigoOrigemProposta,
        @WebParam(name = "filtroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoType.FiltroContrato> filtroContrato,
        @WebParam(name = "suseps", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoType.Suseps> suseps)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param codigoOrigemProposta
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param numeroContrato
     * @param suseps
     * @param nomePessoa
     * @param filtroContrato
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterContratoCompletoResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterContratoCompleto")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterContratoCompleto", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterContratoCompletoType")
    @ResponseWrapper(localName = "obterContratoCompletoResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterContratoCompletoResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoCompletoResponseType.Pessoa> obterContratoCompleto(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroContrato,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa,
        @WebParam(name = "codigoOrigemProposta", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String codigoOrigemProposta,
        @WebParam(name = "filtroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoCompletoType.FiltroContrato> filtroContrato,
        @WebParam(name = "suseps", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterContratoCompletoType.Suseps> suseps)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param nomePessoa
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterPapeisPessoasResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterPapeisPessoas")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterPapeisPessoas", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPapeisPessoasType")
    @ResponseWrapper(localName = "obterPapeisPessoasResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPapeisPessoasResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPapeisPessoasResponseType.Pessoa> obterPapeisPessoas(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param nomePessoa
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterPessoasResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterPessoas")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterPessoas", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasType")
    @ResponseWrapper(localName = "obterPessoasResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPessoasResponseType.Pessoa> obterPessoas(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param nomePessoa
     * @param codigoGrupoAgregacaoPessoa
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterPessoasCompletoResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterPessoasCompleto")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterPessoasCompleto", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasCompletoType")
    @ResponseWrapper(localName = "obterPessoasCompletoResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasCompletoResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPessoasCompletoResponseType.Pessoa> obterPessoasCompleto(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa,
        @WebParam(name = "codigoGrupoAgregacaoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long codigoGrupoAgregacaoPessoa)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param codigoOrigemProposta
     * @param numeroPessoa
     * @param tipoPessoa
     * @param numeroOrdemCnpj
     * @param numeroContrato
     * @param suseps
     * @param nomePessoa
     * @param filtroContrato
     * @param codigoGrupoAgregacaoPessoa
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterPessoasContratosCompletoResponseType.Pessoa>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterPessoasContratosCompleto")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterPessoasContratosCompleto", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasContratosCompletoType")
    @ResponseWrapper(localName = "obterPessoasContratosCompletoResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterPessoasContratosCompletoResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPessoasContratosCompletoResponseType.Pessoa> obterPessoasContratosCompleto(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroContrato,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "nomePessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String nomePessoa,
        @WebParam(name = "tipoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String tipoPessoa,
        @WebParam(name = "codigoGrupoAgregacaoPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long codigoGrupoAgregacaoPessoa,
        @WebParam(name = "codigoOrigemProposta", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String codigoOrigemProposta,
        @WebParam(name = "filtroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPessoasContratosCompletoType.FiltroContrato> filtroContrato,
        @WebParam(name = "suseps", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterPessoasContratosCompletoType.Suseps> suseps)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroCnae
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.ObterDadosCnaeResponseType.DadosCnae
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterDadosCnae")
    @WebResult(name = "dadosCnae", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterDadosCnae", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterDadosCnaeType")
    @ResponseWrapper(localName = "obterDadosCnaeResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterDadosCnaeResponseType")
    public com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterDadosCnaeResponseType.DadosCnae obterDadosCnae(
        @WebParam(name = "numeroCnae", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        int numeroCnae)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterCorretorResponseType.Corretor>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterCorretor")
    @WebResult(name = "corretor", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterCorretor", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterCorretorType")
    @ResponseWrapper(localName = "obterCorretorResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterCorretorResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterCorretorResponseType.Corretor> obterCorretor(
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        long numeroPessoa)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterFuncionarioPrestadorResponseType.DadosFuncPrest>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterFuncionarioPrestador")
    @WebResult(name = "dadosFuncPrest", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterFuncionarioPrestador", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterFuncionarioPrestadorType")
    @ResponseWrapper(localName = "obterFuncionarioPrestadorResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterFuncionarioPrestadorResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterFuncionarioPrestadorResponseType.DadosFuncPrest> obterFuncionarioPrestador(
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        long numeroPessoa)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroPessoa
     * @param numeroOrdemCnpj
     * @param suseps
     * @param filtroContrato
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.wsdl.ObterListaContratosResponseType.Contratos>
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterListaContratos")
    @WebResult(name = "contratos", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterListaContratos", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterListaContratosType")
    @ResponseWrapper(localName = "obterListaContratosResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterListaContratosResponseType")
    public List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterListaContratosResponseType.Contratos> obterListaContratos(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "numeroPessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroPessoa,
        @WebParam(name = "filtroContrato", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterListaContratosType.FiltroContrato> filtroContrato,
        @WebParam(name = "suseps", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        List<com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterListaContratosType.Suseps> suseps)
        throws PortoSeguroFaultInfo
    ;

    /**
     * 
     * @param numeroOrdemCnpj
     * @param numeroCpfouCnpj
     * @param digitoCpfouCnpj
     * @param registroNacionalEstrangeiro
     * @param placa
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.ObterDadosVeiculoResponseType.Pessoa
     * @throws PortoSeguroFaultInfo
     */
    @WebMethod(action = "http://www.portoseguro.com.br/bi/integration/ConsultaDadosBCPABCS/V2_0/obterDadosVeiculo")
    @WebResult(name = "pessoa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
    @RequestWrapper(localName = "obterDadosVeiculo", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterDadosVeiculoType")
    @ResponseWrapper(localName = "obterDadosVeiculoResponse", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ObterDadosVeiculoResponseType")
    public com.porto.portocom.portal.cliente.v1.wsdl.bcp.ObterDadosVeiculoResponseType.Pessoa obterDadosVeiculo(
        @WebParam(name = "numeroCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Long numeroCpfouCnpj,
        @WebParam(name = "numeroOrdemCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short numeroOrdemCnpj,
        @WebParam(name = "digitoCpfouCnpj", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        Short digitoCpfouCnpj,
        @WebParam(name = "registroNacionalEstrangeiro", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String registroNacionalEstrangeiro,
        @WebParam(name = "placa", targetNamespace = "http://www.portoseguro.com.br/bi/integrations/ConsultaDadosBCPEBS/V2_0/")
        String placa)
        throws PortoSeguroFaultInfo
    ;

}
