
package com.porto.portocom.portal.cliente.v1.wsdl.conquista;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteArenaWSImplService", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", wsdlLocation = "http://waststcorp:80/arenaservicos/ClienteArenaWSImplService?wsdl")
public class ClienteArenaWSImplService
    extends Service
{

    private final static URL CLIENTEARENAWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTEARENAWSIMPLSERVICE_EXCEPTION;
    private final static QName CLIENTEARENAWSIMPLSERVICE_QNAME = new QName("http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", "ClienteArenaWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://waststcorp:80/arenaservicos/ClienteArenaWSImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTEARENAWSIMPLSERVICE_WSDL_LOCATION = url;
        CLIENTEARENAWSIMPLSERVICE_EXCEPTION = e;
    }

    public ClienteArenaWSImplService() {
        super(__getWsdlLocation(), CLIENTEARENAWSIMPLSERVICE_QNAME);
    }

    public ClienteArenaWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTEARENAWSIMPLSERVICE_QNAME, features);
    }

    public ClienteArenaWSImplService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTEARENAWSIMPLSERVICE_QNAME);
    }

    public ClienteArenaWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTEARENAWSIMPLSERVICE_QNAME, features);
    }

    public ClienteArenaWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteArenaWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteArenaWSImpl
     */
    @WebEndpoint(name = "ClienteArenaWSImplPort")
    public ClienteArenaWSImpl getClienteArenaWSImplPort() {
        return super.getPort(new QName("http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", "ClienteArenaWSImplPort"), ClienteArenaWSImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteArenaWSImpl
     */
    @WebEndpoint(name = "ClienteArenaWSImplPort")
    public ClienteArenaWSImpl getClienteArenaWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", "ClienteArenaWSImplPort"), ClienteArenaWSImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTEARENAWSIMPLSERVICE_EXCEPTION!= null) {
            throw CLIENTEARENAWSIMPLSERVICE_EXCEPTION;
        }
        return CLIENTEARENAWSIMPLSERVICE_WSDL_LOCATION;
    }

}
