
package com.porto.portocom.portal.cliente.v1.wsdl.conquista;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteArenaWSImpl", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteArenaWSImpl {


    /**
     * 
     * @param cadastrarClienteArena
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.conquista.CadastrarClienteArenaResponseType
     * @throws CadastrarClienteArenaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarClienteArena", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.CadastrarClienteArena")
    @ResponseWrapper(localName = "cadastrarClienteArenaResponse", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.CadastrarClienteArenaResponse")
    @Action(input = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaRequest", output = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaResponse", fault = {
        @FaultAction(className = CadastrarClienteArenaException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArena/Fault/CadastrarClienteArenaException")
    })
    public CadastrarClienteArenaResponseType cadastrarClienteArena(
        @WebParam(name = "cadastrarClienteArena", targetNamespace = "")
        CadastrarClienteArenaRequestType cadastrarClienteArena)
        throws CadastrarClienteArenaException_Exception
    ;

    /**
     * 
     * @param cadastrarClienteArenaValidation
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.conquista.CadastrarClienteArenaResponseType
     * @throws InvocationTargetException_Exception
     * @throws IllegalAccessException_Exception
     * @throws CadastrarClienteArenaException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cadastrarClienteArenaValidation", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.CadastrarClienteArenaValidation")
    @ResponseWrapper(localName = "cadastrarClienteArenaValidationResponse", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.CadastrarClienteArenaValidationResponse")
    @Action(input = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaValidationRequest", output = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaValidationResponse", fault = {
        @FaultAction(className = InvocationTargetException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaValidation/Fault/InvocationTargetException"),
        @FaultAction(className = CadastrarClienteArenaException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaValidation/Fault/CadastrarClienteArenaException"),
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/cadastrarClienteArenaValidation/Fault/IllegalAccessException")
    })
    public CadastrarClienteArenaResponseType cadastrarClienteArenaValidation(
        @WebParam(name = "cadastrarClienteArenaValidation", targetNamespace = "")
        CadastrarClienteArenaRequestType cadastrarClienteArenaValidation)
        throws CadastrarClienteArenaException_Exception, IllegalAccessException_Exception, InvocationTargetException_Exception
    ;

    /**
     * 
     * @param isClienteArenaCadastrado
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.conquista.IsClienteCadastradoResponseType
     * @throws ConsultarClienteArenaCadastradoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isClienteArenaCadastrado", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.IsClienteArenaCadastrado")
    @ResponseWrapper(localName = "isClienteArenaCadastradoResponse", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.IsClienteArenaCadastradoResponse")
    @Action(input = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/isClienteArenaCadastradoRequest", output = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/isClienteArenaCadastradoResponse", fault = {
        @FaultAction(className = ConsultarClienteArenaCadastradoException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/isClienteArenaCadastrado/Fault/ConsultarClienteArenaCadastradoException")
    })
    public IsClienteCadastradoResponseType isClienteArenaCadastrado(
        @WebParam(name = "isClienteArenaCadastrado", targetNamespace = "")
        IsClienteCadastradoRequestType isClienteArenaCadastrado)
        throws ConsultarClienteArenaCadastradoException_Exception
    ;

    /**
     * 
     * @param isClienteArenaCadastrado
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.conquista.IsClienteCadastradoResponseType
     * @throws ConsultarClienteArenaCadastradoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterDadosClienteArenaCadastrado", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.ObterDadosClienteArenaCadastrado")
    @ResponseWrapper(localName = "obterDadosClienteArenaCadastradoResponse", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.ObterDadosClienteArenaCadastradoResponse")
    @Action(input = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaCadastradoRequest", output = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaCadastradoResponse", fault = {
        @FaultAction(className = ConsultarClienteArenaCadastradoException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaCadastrado/Fault/ConsultarClienteArenaCadastradoException")
    })
    public IsClienteCadastradoResponseType obterDadosClienteArenaCadastrado(
        @WebParam(name = "isClienteArenaCadastrado", targetNamespace = "")
        IsClienteCadastradoRequestType isClienteArenaCadastrado)
        throws ConsultarClienteArenaCadastradoException_Exception
    ;

    /**
     * 
     * @param susep
     * @param isClienteArenaCadastrado
     * @return
     *     returns com.porto.financeiro.portopar.arenaservicos.soap.service.impl.IsClienteCadastradoResponseType
     * @throws ConsultarClienteArenaCadastradoException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterDadosClienteArenaVinculado", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.ObterDadosClienteArenaVinculado")
    @ResponseWrapper(localName = "obterDadosClienteArenaVinculadoResponse", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.conquista.ObterDadosClienteArenaVinculadoResponse")
    @Action(input = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaVinculadoRequest", output = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaVinculadoResponse", fault = {
        @FaultAction(className = ConsultarClienteArenaCadastradoException_Exception.class, value = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/ClienteArenaWSImpl/obterDadosClienteArenaVinculado/Fault/ConsultarClienteArenaCadastradoException")
    })
    public IsClienteCadastradoResponseType obterDadosClienteArenaVinculado(
        @WebParam(name = "isClienteArenaCadastrado", targetNamespace = "")
        IsClienteCadastradoRequestType isClienteArenaCadastrado,
        @WebParam(name = "susep", targetNamespace = "")
        String susep)
        throws ConsultarClienteArenaCadastradoException_Exception
    ;

}
