
package com.porto.portocom.portal.cliente.v1.wsdl.conquista;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvocationTargetException", targetNamespace = "http://impl.service.soap.arenaservicos.portopar.financeiro.porto.com/")
public class InvocationTargetException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvocationTargetException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvocationTargetException_Exception(String message, InvocationTargetException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvocationTargetException_Exception(String message, InvocationTargetException faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.porto.portocom.portal.cliente.wsdl.conquista.InvocationTargetException
     */
    public InvocationTargetException getFaultInfo() {
        return faultInfo;
    }

}
