[template]
src = "application.properties.tmpl"
dest = "/deployments/application-infra.properties"
keys = [
	"/server/servlet/context/path",
    "/server/port",
    "/management/server/address",
    "/management/server/port",
    "/management/security/enabled",
    "/management/endpoints/web/exposure/include",
    "/management/health/defaults/enable",
    "/management/endpoints/web/base/path",
    "/spring/application/name",
	"/integration/portallog/url",
 	"/integration/portallog/isfile",
 	"/integration/sso/host/bcc/url",
 	"/integration/sso/parametro/grant/type",
	"/integration/sso/parametro/client/id",
	"/integration/sso/parametro/client/secret",
	"/integration/sso/parametro/username",
	"/integration/sso/parametro/password",
	"/integration/sso/parametro/scope",
	"/transacional/jpa/hibernate/ddl/auto",
	"/transacional/datasource/driver/class/name",
	"/transacional/datasource/url",
	"/transacional/datasource/username",
	"/transacional/datasource/password",
	"/wemclient/datasource/schema",
	"/spring/cache/type",
	"/spring/cache/redis/time/to/live",
	"/spring/redis/database",
	"/spring/redis/host",
	"/spring/redis/password",
	"/spring/redis/pool/max",
	"/spring/redis/pool/max/idle",
	"/spring/redis/pool/max/wait",
	"/spring/redis/pool/min/idle",
	"/spring/redis/port",
	"/spring/redis/timeout",
	"/parametros/cache",
	"/mensagem/cache"
]
