
package com.porto.portocom.portal.cliente.v1.wsdl.vdo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.porto.portocom.portal.cliente.v1.wsdl.vdo.common.VendaOnlineResponse;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaOnlinePesquisaCotacaoEndPoint", targetNamespace = "http://ws.integracao.vendaonline.marketing.porto.com")
@XmlSeeAlso({ com.porto.portocom.portal.cliente.v1.wsdl.vdo.common.ObjectFactory.class,
		com.porto.portocom.portal.cliente.v1.wsdl.vdo.ObjectFactory.class })
public interface VendaOnlinePesquisaCotacaoEndPoint {

	/**
	 * 
	 * @param numeroCpfCnpj
	 * @param ordemCnpj
	 * @param digitoCpfCnpj
	 * @return returns com.porto.portocom.portal.cliente.wsdl.vdo.common.VendaOnlineResponse
	 */
	@WebMethod(action = "pesquisaCotacoesVendaOnline")
	@WebResult(name = "pesquisaCotacoesVendaOnlineReturn", targetNamespace = "")
	@RequestWrapper(localName = "pesquisaCotacoesVendaOnline", targetNamespace = "http://ws.integracao.vendaonline.marketing.porto.com", className = "com.porto.portocom.portal.cliente.v1.wsdl.vdo.PesquisaCotacoesVendaOnline")
	@ResponseWrapper(localName = "pesquisaCotacoesVendaOnlineResponse", targetNamespace = "http://ws.integracao.vendaonline.marketing.porto.com", className = "com.porto.portocom.portal.cliente.v1.wsdl.vdo.PesquisaCotacoesVendaOnlineResponse")
	public VendaOnlineResponse pesquisaCotacoesVendaOnline(
			@WebParam(name = "numeroCpfCnpj", targetNamespace = "") Integer numeroCpfCnpj,
			@WebParam(name = "ordemCnpj", targetNamespace = "") Integer ordemCnpj,
			@WebParam(name = "digitoCpfCnpj", targetNamespace = "") Integer digitoCpfCnpj);

}
