
package com.porto.portocom.portal.cliente.v1.wsdl.investimento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarCotistaServiceService", targetNamespace = "http://service.portopar.financeiro.porto.com", wsdlLocation = "http://was8tstpparconsfin/portopar/services/ConsultarCotistaService/wsdl/ConsultarCotistaService.wsdl")
public class ConsultarCotistaServiceService
    extends Service
{

    private final static URL CONSULTARCOTISTASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONSULTARCOTISTASERVICESERVICE_EXCEPTION;
    private final static QName CONSULTARCOTISTASERVICESERVICE_QNAME = new QName("http://service.portopar.financeiro.porto.com", "ConsultarCotistaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://was8tstpparconsfin/portopar/services/ConsultarCotistaService/wsdl/ConsultarCotistaService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARCOTISTASERVICESERVICE_WSDL_LOCATION = url;
        CONSULTARCOTISTASERVICESERVICE_EXCEPTION = e;
    }

    public ConsultarCotistaServiceService() {
        super(__getWsdlLocation(), CONSULTARCOTISTASERVICESERVICE_QNAME);
    }

    public ConsultarCotistaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARCOTISTASERVICESERVICE_QNAME, features);
    }

    public ConsultarCotistaServiceService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARCOTISTASERVICESERVICE_QNAME);
    }

    public ConsultarCotistaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARCOTISTASERVICESERVICE_QNAME, features);
    }

    public ConsultarCotistaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCotistaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarCotistaService
     */
    @WebEndpoint(name = "ConsultarCotistaService")
    public ConsultarCotistaService getConsultarCotistaService() {
        return super.getPort(new QName("http://service.portopar.financeiro.porto.com", "ConsultarCotistaService"), ConsultarCotistaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCotistaService
     */
    @WebEndpoint(name = "ConsultarCotistaService")
    public ConsultarCotistaService getConsultarCotistaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.portopar.financeiro.porto.com", "ConsultarCotistaService"), ConsultarCotistaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARCOTISTASERVICESERVICE_EXCEPTION!= null) {
            throw CONSULTARCOTISTASERVICESERVICE_EXCEPTION;
        }
        return CONSULTARCOTISTASERVICESERVICE_WSDL_LOCATION;
    }

}
