
package com.porto.portocom.portal.cliente.v1.wsdl.investimento;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ConsultarCotistaServiceException", targetNamespace = "http://exception.portopar.financeiro.porto.com")
public class ConsultarCotistaServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ConsultarCotistaServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ConsultarCotistaServiceException_Exception(String message, ConsultarCotistaServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ConsultarCotistaServiceException_Exception(String message, ConsultarCotistaServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdlConsultaCotista.ConsultarCotistaServiceException
     */
    public ConsultarCotistaServiceException getFaultInfo() {
        return faultInfo;
    }

}
