
package com.porto.portocom.portal.cliente.v1.wsdl.investimento;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarCotistaService", targetNamespace = "http://service.portopar.financeiro.porto.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarCotistaService {


    /**
     * 
     * @param conta
     * @param agencia
     * @return
     *     returns wsdlConsultaCotista.CotistaServiceVO
     * @throws ConsultarCotistaServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "consultaCotistaPorContratoReturn", targetNamespace = "http://service.portopar.financeiro.porto.com")
    @RequestWrapper(localName = "consultaCotistaPorContrato", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaPorContrato")
    @ResponseWrapper(localName = "consultaCotistaPorContratoResponse", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaPorContratoResponse")
    public CotistaServiceVO consultaCotistaPorContrato(
        @WebParam(name = "agencia", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String agencia,
        @WebParam(name = "conta", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String conta)
        throws ConsultarCotistaServiceException_Exception
    ;

    /**
     * 
     * @param numeroCpfCnpj
     * @param ordemCnpj
     * @param digitoCpfCnpj
     * @return
     *     returns java.util.List<wsdlConsultaCotista.CotistaCompletoServiceVO>
     * @throws ConsultarCotistaServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "consultaCotistaCompletoPorCpfCnpjReturn", targetNamespace = "http://service.portopar.financeiro.porto.com")
    @RequestWrapper(localName = "consultaCotistaCompletoPorCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaCompletoPorCpfCnpj")
    @ResponseWrapper(localName = "consultaCotistaCompletoPorCpfCnpjResponse", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaCompletoPorCpfCnpjResponse")
    public List<CotistaCompletoServiceVO> consultaCotistaCompletoPorCpfCnpj(
        @WebParam(name = "numeroCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String numeroCpfCnpj,
        @WebParam(name = "ordemCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String ordemCnpj,
        @WebParam(name = "digitoCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String digitoCpfCnpj)
        throws ConsultarCotistaServiceException_Exception
    ;

    /**
     * 
     * @param numeroCpfCnpj
     * @param ordemCnpj
     * @param digitoCpfCnpj
     * @return
     *     returns java.util.List<wsdlConsultaCotista.CotistaServiceVO>
     * @throws ConsultarCotistaServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "consultaCotistaPorCpfCnpjReturn", targetNamespace = "http://service.portopar.financeiro.porto.com")
    @RequestWrapper(localName = "consultaCotistaPorCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaPorCpfCnpj")
    @ResponseWrapper(localName = "consultaCotistaPorCpfCnpjResponse", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaPorCpfCnpjResponse")
    public List<CotistaServiceVO> consultaCotistaPorCpfCnpj(
        @WebParam(name = "numeroCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String numeroCpfCnpj,
        @WebParam(name = "ordemCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String ordemCnpj,
        @WebParam(name = "digitoCpfCnpj", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String digitoCpfCnpj)
        throws ConsultarCotistaServiceException_Exception
    ;

    /**
     * 
     * @param conta
     * @param agencia
     * @return
     *     returns wsdlConsultaCotista.CotistaCompletoServiceVO
     * @throws ConsultarCotistaServiceException_Exception
     */
    @WebMethod
    @WebResult(name = "consultaCotistaCompletoPorContratoReturn", targetNamespace = "http://service.portopar.financeiro.porto.com")
    @RequestWrapper(localName = "consultaCotistaCompletoPorContrato", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaCompletoPorContrato")
    @ResponseWrapper(localName = "consultaCotistaCompletoPorContratoResponse", targetNamespace = "http://service.portopar.financeiro.porto.com", className = "wsdlConsultaCotista.ConsultaCotistaCompletoPorContratoResponse")
    public CotistaCompletoServiceVO consultaCotistaCompletoPorContrato(
        @WebParam(name = "agencia", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String agencia,
        @WebParam(name = "conta", targetNamespace = "http://service.portopar.financeiro.porto.com")
        String conta)
        throws ConsultarCotistaServiceException_Exception
    ;

}
