
package com.porto.portocom.portal.cliente.v1.wsdl.ldap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PortalClienteService", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", wsdlLocation = "http://li201.portoseguro.brasil/servicoportalcliente/PortalClienteService/WEB-INF/wsdl/wsdl/PortalClienteService.wsdl")
public class PortalClienteService
    extends Service
{

    private final static URL PORTALCLIENTESERVICE_WSDL_LOCATION;
    private final static WebServiceException PORTALCLIENTESERVICE_EXCEPTION;
    private final static QName PORTALCLIENTESERVICE_QNAME = new QName("http://service.portalcliente.seguranca.porto.com/", "PortalClienteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://li201.portoseguro.brasil/servicoportalcliente/PortalClienteService/WEB-INF/wsdl/wsdl/PortalClienteService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PORTALCLIENTESERVICE_WSDL_LOCATION = url;
        PORTALCLIENTESERVICE_EXCEPTION = e;
    }

    public PortalClienteService() {
        super(__getWsdlLocation(), PORTALCLIENTESERVICE_QNAME);
    }

    public PortalClienteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PORTALCLIENTESERVICE_QNAME, features);
    }

    public PortalClienteService(URL wsdlLocation) {
        super(wsdlLocation, PORTALCLIENTESERVICE_QNAME);
    }

    public PortalClienteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PORTALCLIENTESERVICE_QNAME, features);
    }

    public PortalClienteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PortalClienteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PortalClienteDelegate
     */
    @WebEndpoint(name = "PortalClientePort")
    public PortalClienteDelegate getPortalClientePort() {
        return super.getPort(new QName("http://service.portalcliente.seguranca.porto.com/", "PortalClientePort"), PortalClienteDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PortalClienteDelegate
     */
    @WebEndpoint(name = "PortalClientePort")
    public PortalClienteDelegate getPortalClientePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.portalcliente.seguranca.porto.com/", "PortalClientePort"), PortalClienteDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PORTALCLIENTESERVICE_EXCEPTION!= null) {
            throw PORTALCLIENTESERVICE_EXCEPTION;
        }
        return PORTALCLIENTESERVICE_WSDL_LOCATION;
    }

}
