
package com.porto.portocom.portal.cliente.v1.wsdl.ldap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortalClienteDelegate", targetNamespace = "http://service.portalcliente.seguranca.porto.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortalClienteDelegate {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "autenticarUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AutenticarUsuario")
    @ResponseWrapper(localName = "autenticarUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AutenticarUsuarioResponse")
    public String autenticarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        LoginVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.GeraSenhaReturn
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarUsuario")
    @ResponseWrapper(localName = "criarUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarUsuarioResponse")
    public GeraSenhaReturn criarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaAcessoVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.RetornoVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarAtualizarUsuarioComSenha", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarAtualizarUsuarioComSenha")
    @ResponseWrapper(localName = "criarAtualizarUsuarioComSenhaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarAtualizarUsuarioComSenhaResponse")
    public RetornoVO criarAtualizarUsuarioComSenha(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaAcessoComSenhaVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.RetornoVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarUsuarioComSenha", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarUsuarioComSenha")
    @ResponseWrapper(localName = "criarUsuarioComSenhaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarUsuarioComSenhaResponse")
    public RetornoVO criarUsuarioComSenha(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaAcessoComSenhaVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarPapelPermissaoProduto", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarPapelPermissaoProduto")
    @ResponseWrapper(localName = "criarPapelPermissaoProdutoResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarPapelPermissaoProdutoResponse")
    public String criarPapelPermissaoProduto(
        @WebParam(name = "arg0", targetNamespace = "")
        PapelPermissaoProdutoVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atrelarServicosPermissao", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtrelarServicosPermissao")
    @ResponseWrapper(localName = "atrelarServicosPermissaoResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtrelarServicosPermissaoResponse")
    public String atrelarServicosPermissao(
        @WebParam(name = "arg0", targetNamespace = "")
        CadastroServicoPermissaoVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.ClienteVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ConsultarUsuario")
    @ResponseWrapper(localName = "consultarUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ConsultarUsuarioResponse")
    public ClienteVO consultarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "apagarUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ApagarUsuario")
    @ResponseWrapper(localName = "apagarUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ApagarUsuarioResponse")
    public String apagarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "desbloquearUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.DesbloquearUsuario")
    @ResponseWrapper(localName = "desbloquearUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.DesbloquearUsuarioResponse")
    public String desbloquearUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.ResultVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterarSenha", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarSenha")
    @ResponseWrapper(localName = "alterarSenhaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarSenhaResponse")
    public ResultVO alterarSenha(
        @WebParam(name = "arg0", targetNamespace = "")
        NovaSenhaVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bloquearUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.BloquearUsuario")
    @ResponseWrapper(localName = "bloquearUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.BloquearUsuarioResponse")
    public String bloquearUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.RetornoVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "incluirDocumentoPorUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.IncluirDocumentoPorUsuario")
    @ResponseWrapper(localName = "incluirDocumentoPorUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.IncluirDocumentoPorUsuarioResponse")
    public RetornoVO incluirDocumentoPorUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        VinculoProdutoVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.RetornoVO
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "excluirDocumentoPorUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ExcluirDocumentoPorUsuario")
    @ResponseWrapper(localName = "excluirDocumentoPorUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ExcluirDocumentoPorUsuarioResponse")
    public RetornoVO excluirDocumentoPorUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        VinculoProdutoVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterarServico", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarServico")
    @ResponseWrapper(localName = "alterarServicoResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarServicoResponse")
    public String alterarServico(
        @WebParam(name = "arg0", targetNamespace = "")
        AlteraUrlVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "alterarPapel", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarPapel")
    @ResponseWrapper(localName = "alterarPapelResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AlterarPapelResponse")
    public String alterarPapel(
        @WebParam(name = "arg0", targetNamespace = "")
        AlteraPapelVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws PortalClienteException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atualizarSenha", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarSenha")
    @ResponseWrapper(localName = "atualizarSenhaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarSenhaResponse")
    public String atualizarSenha(
        @WebParam(name = "arg0", targetNamespace = "")
        NovaSenhaVO arg0)
        throws PortalClienteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.GeraSenhaReturn
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gerarSenha", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.GerarSenha")
    @ResponseWrapper(localName = "gerarSenhaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.GerarSenhaResponse")
    public GeraSenhaReturn gerarSenha(
        @WebParam(name = "arg0", targetNamespace = "")
        UsuarioVO arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.porto.portocom.portal.cliente.v1.wsdl.ldap.PapelVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPapelPermissaoServicos", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.GetPapelPermissaoServicos")
    @ResponseWrapper(localName = "getPapelPermissaoServicosResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.GetPapelPermissaoServicosResponse")
    public List<PapelVO> getPapelPermissaoServicos();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atualizarPermissaoServicos", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarPermissaoServicos")
    @ResponseWrapper(localName = "atualizarPermissaoServicosResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarPermissaoServicosResponse")
    public String atualizarPermissaoServicos(
        @WebParam(name = "arg0", targetNamespace = "")
        CadastroServicoPermissaoVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atualizarUsuario", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarUsuario")
    @ResponseWrapper(localName = "atualizarUsuarioResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.AtualizarUsuarioResponse")
    public String atualizarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        AtualizaUsuarioVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "criarSistema", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarSistema")
    @ResponseWrapper(localName = "criarSistemaResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.CriarSistemaResponse")
    public String criarSistema(
        @WebParam(name = "arg0", targetNamespace = "")
        CadastroSistemaVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.RetornoListaServicoPorPermissaoVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarServicosPermissao", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ListarServicosPermissao")
    @ResponseWrapper(localName = "listarServicosPermissaoResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ListarServicosPermissaoResponse")
    public RetornoListaServicoPorPermissaoVO listarServicosPermissao(
        @WebParam(name = "arg0", targetNamespace = "")
        PermissaoVO arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.v1.wsdl.ldap.ListaClienteVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterClientes", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ObterClientes")
    @ResponseWrapper(localName = "obterClientesResponse", targetNamespace = "http://service.portalcliente.seguranca.porto.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.ldap.ObterClientesResponse")
    public ListaClienteVO obterClientes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
