
package com.porto.portocom.portal.cliente.v1.wsdl.ldap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PortalClienteException", targetNamespace = "http://service.portalcliente.seguranca.porto.com/")
public class PortalClienteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PortalClienteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PortalClienteException_Exception(String message, PortalClienteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PortalClienteException_Exception(String message, PortalClienteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.porto.portocom.portal.cliente.v1.wsdl.ldap.PortalClienteException
     */
    public PortalClienteException getFaultInfo() {
        return faultInfo;
    }

}
