
package com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CartaoWebPortalService", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", wsdlLocation = "http://waststcorp.portoseguro.brasil/autoatendimentocartaoWS/CartaoWebPortalService/CartaoWebPortalService.wsdl")
public class CartaoWebPortalService
    extends Service
{

    private final static URL CARTAOWEBPORTALSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARTAOWEBPORTALSERVICE_EXCEPTION;
    private final static QName CARTAOWEBPORTALSERVICE_QNAME = new QName("http://ws.cartaoweb.cartoes.financeiro.com/", "CartaoWebPortalService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://waststcorp.portoseguro.brasil/autoatendimentocartaoWS/CartaoWebPortalService/CartaoWebPortalService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTAOWEBPORTALSERVICE_WSDL_LOCATION = url;
        CARTAOWEBPORTALSERVICE_EXCEPTION = e;
    }

    public CartaoWebPortalService() {
        super(__getWsdlLocation(), CARTAOWEBPORTALSERVICE_QNAME);
    }

    public CartaoWebPortalService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTAOWEBPORTALSERVICE_QNAME, features);
    }

    public CartaoWebPortalService(URL wsdlLocation) {
        super(wsdlLocation, CARTAOWEBPORTALSERVICE_QNAME);
    }

    public CartaoWebPortalService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTAOWEBPORTALSERVICE_QNAME, features);
    }

    public CartaoWebPortalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartaoWebPortalService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartaoWebPortal
     */
    @WebEndpoint(name = "CartaoWebPortalPort")
    public CartaoWebPortal getCartaoWebPortalPort() {
        return super.getPort(new QName("http://ws.cartaoweb.cartoes.financeiro.com/", "CartaoWebPortalPort"), CartaoWebPortal.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartaoWebPortal
     */
    @WebEndpoint(name = "CartaoWebPortalPort")
    public CartaoWebPortal getCartaoWebPortalPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cartaoweb.cartoes.financeiro.com/", "CartaoWebPortalPort"), CartaoWebPortal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTAOWEBPORTALSERVICE_EXCEPTION!= null) {
            throw CARTAOWEBPORTALSERVICE_EXCEPTION;
        }
        return CARTAOWEBPORTALSERVICE_WSDL_LOCATION;
    }

}
