
package com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CartaoWebPortal", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CartaoWebPortal {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.complementocartoes.ContaCartaoRetornoVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaContaCartao", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartao")
    @ResponseWrapper(localName = "consultaContaCartaoResponse", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoResponse")
    @Action(input = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoRequest", output = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoResponse")
    public ContaCartaoRetornoVO consultaContaCartao(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaCartaoParamentroVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.complementocartoes.ContaCartaoComEmailRetornoVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaContaCartaoComAdicional", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicional")
    @ResponseWrapper(localName = "consultaContaCartaoComAdicionalResponse", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicionalResponse")
    @Action(input = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalRequest", output = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalResponse")
    public ContaCartaoComEmailRetornoVO consultaContaCartaoComAdicional(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaCartaoParamentroVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.complementocartoes.ContaCartaoRetornoVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaContaCartaoComAdicionalPJ", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicionalPJ")
    @ResponseWrapper(localName = "consultaContaCartaoComAdicionalPJResponse", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicionalPJResponse")
    @Action(input = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalPJRequest", output = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalPJResponse")
    public ContaCartaoRetornoVO consultaContaCartaoComAdicionalPJ(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaCartaoParamentroVO arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.porto.portocom.portal.cliente.wsdl.complementocartoes.ContaCartaoRetornoVOV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaContaCartaoComAdicionalV2", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicionalV2")
    @ResponseWrapper(localName = "consultaContaCartaoComAdicionalV2Response", targetNamespace = "http://ws.cartaoweb.cartoes.financeiro.com/", className = "com.porto.portocom.portal.cliente.v1.wsdl.complementocartoes.ConsultaContaCartaoComAdicionalV2Response")
    @Action(input = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalV2Request", output = "http://ws.cartaoweb.cartoes.financeiro.com/CartaoWebPortal/consultaContaCartaoComAdicionalV2Response")
    public ContaCartaoRetornoVOV2 consultaContaCartaoComAdicionalV2(
        @WebParam(name = "arg0", targetNamespace = "")
        ContaCartaoParamentroVO arg0);

}
